name = input("Введите ваше имя: ")
print(name)
age = input("Введите ваш возраст: ")
print(age)
work = input("Введите ваше место работы: ")
print(f"Данные о пользователе: имя - {name}, возраст - {age}, место работы - {work}")